name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true
      
      - run: go test -race -count=3 -v ./...

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
    

  vulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: ''
          go-version-file: go.mod
    